name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'mã CRD google'
        required: true
      pincode:
        description: 'Mật khẩu 6 chữ'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
