name: Windows-SV-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Mã CRD google'
        required: true
      pincode:
        description: 'Mật khẩu 6 chữ'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Khởi tạo và thiết lập
      run: ./setup.ps1
    - name: Bắt đầu khởi chạy CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Thời gian còn lại của VPS
      run: ./timeout.ps1
